alter table payments_tariffs drop foreign key FKfu5658f1l4mtgyx0dcg99axvf;
alter table payments_tariffs drop foreign key FKaohjgoth0s3c0bxddtws9hdn8;
alter table tokens drop foreign key FK2dylsfo39lgjyqml2tbe0b0ss;
alter table user_roles drop foreign key FKh8ciramu9cc9q3qcqiv4ue8a6;
alter table user_roles drop foreign key FKhfh9dx7w3ubf1co1vdev94g3f;
alter table user_balances drop foreign key FKfw60yn584dehknpjjufbl72uo;
drop table if exists payments;
drop table if exists payments_tariffs;
drop table if exists roles;
drop table if exists tariffs;
drop table if exists tokens;
drop table if exists user_roles;
drop table if exists user_balances;
drop table if exists users;
create table payments (id bigint not null auto_increment, electricity_sum varchar(255), electricity_value_current_month double precision not null, home_mates integer not null, internet_sum varchar(255), internet_value_current_month double precision not null, payment_date datetime, rent_rate_sum varchar(255), rent_sum varchar(255), water_cold_sum varchar(255), water_cold_value_current_month double precision not null, water_out_sum varchar(255), water_out_value_current_month double precision not null, water_warm_sum varchar(255), water_warm_value_current_month double precision not null, primary key (id)) engine=InnoDB;
create table payments_tariffs (payment_id bigint not null, tariff_id bigint not null, primary key (payment_id, tariff_id)) engine=InnoDB;
create table roles (id integer not null auto_increment, role_name varchar(20), primary key (id)) engine=InnoDB;
create table tariffs (id bigint not null auto_increment, date_rate_change datetime, electricity_rate varchar(255), internet_rate varchar(255), rent_rate varchar(255), water_cold_rate varchar(255), water_hot_rate varchar(255), primary key (id)) engine=InnoDB;
create table tokens (id bigint not null auto_increment, active bit not null, creation_date datetime, token varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table user_balances (id bigint not null auto_increment, balance_date datetime, balance_sum_of_balance varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table users (id bigint not null auto_increment, creation_date datetime, password varchar(255), user_email varchar(255), user_name varchar(255), primary key (id)) engine=InnoDB;
alter table payments_tariffs add constraint FKfu5658f1l4mtgyx0dcg99axvf foreign key (tariff_id) references tariffs (id);
alter table payments_tariffs add constraint FKaohjgoth0s3c0bxddtws9hdn8 foreign key (payment_id) references payments (id);
alter table tokens add constraint FK2dylsfo39lgjyqml2tbe0b0ss foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
alter table user_balances add constraint FKfw60yn584dehknpjjufbl72uo foreign key (user_id) references users (id);